get_lowest_price_interval:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: epex_spot
    earliest_start:
      required: false
      selector:
        time:
    earliest_start_post:
      required: false
      selector:
        number:
          min: 0
          max: 2
          step: 1
          unit_of_measurement: days
          mode: box
    latest_end:
      required: false
      selector:
        time:
    latest_end_post:
      required: false
      selector:
        number:
          min: 0
          max: 2
          step: 1
          unit_of_measurement: days
          mode: box
    duration:
      required: true
      example: 01:00:00
      selector:
        duration:
    price_type:
      required: false
      default: market_price
      selector:
        select:
          options:
            - label: Market Price
              value: market_price
            - label: Total Price
              value: total_price
            - label: Import Price
              value: import_price
            - label: Export Price
              value: export_price
get_highest_price_interval:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: epex_spot
    earliest_start:
      required: false
      selector:
        time:
    earliest_start_post:
      required: false
      selector:
        number:
          min: 0
          max: 2
          step: 1
          unit_of_measurement: days
          mode: box
    latest_end:
      required: false
      selector:
        time:
    latest_end_post:
      required: false
      selector:
        number:
          min: 0
          max: 2
          step: 1
          unit_of_measurement: days
          mode: box
    duration:
      required: true
      example: 01:00:00
      selector:
        duration:
    price_type:
      required: false
      default: market_price
      selector:
        select:
          options:
            - label: Market Price
              value: market_price
            - label: Total Price
              value: total_price
            - label: Import Price
              value: import_price
            - label: Export Price
              value: export_price
fetch_data:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: epex_spot
